AllCops:
  NewCops: enable

  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'app/models/concerns/data_event_publishing.rb'

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: ['configure']

Metrics/MethodLength:
  ExcludedMethods: ['add_validation']
  Max: 12

Metrics/AbcSize:
  IgnoredMethods: ['add_validation']



