version: '3'
services:
  db:
    image: postgres
    container_name: db
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: Ngoc@hieu2019
      POSTGRES_USER: hieu123
      POSTGRES_DB: testdb
  web:
    image: test_rail
    container_name: web
    volumes:
      - storage:/coder_alert/tmp
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - DATABASE_HOST=db
      - DATABASE_USER=hieu123
      - DATABASE_PASSWORD=Ngoc@hieu2019
      - DATABASE_NAME=testdb
      - ELASTICSEARCH_URL=elasticsearch
    depends_on:
      - db
      - elasticsearch
    tty: true
    stdin_open: true

  elasticsearch:
    image: elasticsearch:7.9.1
    container_name: elastichsearch
    volumes:
      - .:/coder_alert
      - /coder_alert/tmp
    environment:
      - discovery.type=single-node
      - cluster.name=elasticsearch-rails
      - cluster.routing.allocation.disk.threshold_enabled=false
    ports:
      - "9200:9200"
volumes:
  storage:
  db:
