version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/coder_alert
      - node_modules:/coder_alert/node_modules
      - /coderalert/tmp
    ports:
      - "3000:3000"
    environment:
      - ELASTICSEARCH_URL=elasticsearch
    depends_on:
      - db
      - elasticsearch
    tty: true
    stdin_open: true

  elasticsearch:
    image: elasticsearch:7.9.1
    volumes:
      - .:/coder_alert
    environment:
      - discovery.type=single-node
      - cluster.name=elasticsearch-rails
      - cluster.routing.allocation.disk.threshold_enabled=false
    ports:
      - "9200:9200"

volumes:
  node_modules:

#  delayed_job:
#    build: .
#    command: bash -c "bundle exec rake jobs:work"
#    volumes:
#      - .:/coder_alert
#    depends_on:
#      - db
#    tty: true
#    stdin_open: true
