# for staging environment

version: '3'
services:
  db:
    image: postgres
    container_name: db
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: Ngoc@hieu2019
      POSTGRES_USER: hieu123
      POSTGRES_DB: testdb
  web:
    image: coder_alert:staging
    container_name: web
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-2
        awslogs-group: stagingLogGroup
        awslogs-create-group: "true"
    volumes:
      - storage:/coder_alert/tmp
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=staging
      - DATABASE_HOST=db
      - DATABASE_USER=hieu123
      - DATABASE_PASSWORD=Ngoc@hieu2019
      - DATABASE_NAME=testdb
      - ELASTICSEARCH_URL=elasticsearch
      - RAILS_MASTER_KEY=8e9445d8c00175f14009b3eda769608f
      - RAILS_LOG_TO_STDOUT=true
    depends_on:
      - db
      - elasticsearch
    tty: true
    stdin_open: true
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    ulimits:
      memlock:
        soft: -1
        hard: -1
    container_name: elasticsearch
    volumes:
      - es_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - cluster.name=elasticsearch-rails
      - cluster.routing.allocation.disk.threshold_enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
volumes:
  storage:
  db:
  es_data:
