# for development environment

version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build:
      context: .
      dockerfile: development.Dockerfile
      args:
        image: web
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/coder_alert
      - /coder_alert/tmp
      - node_modules:/coder_alert/node_modules
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - DATABASE_HOST=db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=coder_alert_development
      - ELASTICSEARCH_URL=elasticsearch
    depends_on:
      - db
      - elasticsearch
    tty: true
    stdin_open: true
  delayed_job:
    build:
      context: .
      dockerfile: development.Dockerfile
      args:
        image: delayed_job
    command: bash -c "rake db:migrate && bundle exec rake jobs:work"
    volumes:
      - .:/coder_alert
      - /coder_alert/tmp
    environment:
      - RAILS_ENV=development
      - DATABASE_HOST=db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=coder_alert_development
      - ELASTICSEARCH_URL=elasticsearch
    depends_on:
      - db
    tty: true
    stdin_open: true
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - .:/coder_alert
    environment:
      - discovery.type=single-node
      - cluster.name=elasticsearch-rails
      - cluster.routing.allocation.disk.threshold_enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
volumes:
  node_modules:
